export interface RealWeddingDetail {
  slug: string;
  title: string;
  coupleNames: string;
  city: string;
  state: string;
  venue: string;
  date: string;
  theme: string;
  photographer: string;
  planner: string;
  budget: string;
  guestCount: string;
  shortDescription: string;
  story: string;
  heroImage: string;
  gallery: string[];
  decorHighlights: string;
  ceremonyHighlights: string;
  receptionHighlights: string;
  bridalOutfitDetails: string;
  groomOutfitDetails: string;
  vendors: {
    venue: string;
    photographer: string;
    decorator: string;
    makeupArtist: string;
    catering: string;
    planner?: string;
  };
}

const placeholderGallery = [
  "/images/editorial/hero_venue.png",
  "/images/editorial/garden_wedding.png",
  "/images/editorial/insp_jewelry.png",
  "/images/editorial/vendor_catering.png",
  "/images/editorial/vendor_photo.png",
  "/images/editorial/venue_2.png",
  "/images/editorial/vendor_makeup.png",
  "/images/editorial/venue_3.png",
  "/images/editorial/venue_4.png",
  "/images/editorial/venue_1.png",
  "/images/editorial/royal_wedding.png",
  "/images/editorial/mandap_design.png",
  "/images/editorial/vendor_decoration.png",
  "/images/editorial/vendor_music.png",
  "/images/editorial/minimal_wedding.png",
];

export const realWeddingDetails: Record<string, RealWeddingDetail> = {
  "elegant-city-affair": {
    slug: "elegant-city-affair",
    title: "An Elegant City Affair",
    coupleNames: "Sophia & James",
    city: "Mumbai",
    state: "Maharashtra",
    venue: "The St. Regis",
    date: "September 15, 2025",
    theme: "Luxury",
    photographer: "Lumina Studio",
    planner: "Elite Events",
    budget: "₹40L+",
    guestCount: "450",
    shortDescription: "A sophisticated urban celebration featuring skyline views and minimalist decor.",
    story: "Sophia and James met in the bustling heart of the city, so it was only fitting that they tied the knot amidst the iconic skyline. Their wedding was a masterclass in modern elegance, combining timeless traditions with sleek, contemporary styling. Surrounded by their closest family and friends, the evening was filled with laughter, heartfelt toasts, and an unforgettable dance floor. The couple wanted the focus to be on the stunning views and their love for each other, resulting in a celebration that felt both grand and incredibly intimate.",
    heroImage: "/images/editorial/hero_venue.png",
    gallery: placeholderGallery,
    decorHighlights: "The decor featured cascading white orchids, mirrored aisle runners, and thousands of floating candles. The minimalist approach allowed the venue's natural architecture to shine, while subtle gold accents brought warmth to the space.",
    ceremonyHighlights: "An intimate rooftop exchange of vows at sunset.",
    receptionHighlights: "A grand ballroom reception with a live jazz band.",
    bridalOutfitDetails: "Sophia wore a bespoke silk crepe gown with a sweeping train and structural bodice, paired with heirloom diamond earrings and a dramatic cathedral-length veil.",
    groomOutfitDetails: "James opted for a classic midnight blue tuxedo with a black satin lapel and a custom silk bowtie.",
    vendors: {
      venue: "The St. Regis",
      photographer: "Lumina Studio",
      decorator: "Urban Flora Events",
      makeupArtist: "Glow Beauty Collective",
      catering: "St. Regis Culinary Team",
      planner: "Elite Events",
    },
  },
  "rustic-vineyard-romance": {
    slug: "rustic-vineyard-romance",
    title: "A Picturesque Lakeside Celebration",
    coupleNames: "Emma & Liam",
    city: "Udaipur",
    state: "Rajasthan",
    venue: "Taj Lake Palace",
    date: "October 10, 2025",
    theme: "Royal",
    photographer: "Wanderlust Imagery",
    planner: "Regal Weddings",
    budget: "₹40L+",
    guestCount: "300",
    shortDescription: "A majestic destination wedding set against the serene backdrop of Lake Pichola.",
    story: "Set against the serene waters of Udaipur, Emma and Liam's wedding was a celebration of nature, heritage, and deep connection. The autumn sunset provided a breathtaking backdrop for their heartfelt vows. The reception was a lively, royal feast featuring local ingredients and world-class wine pairings. It was a day where time seemed to slow down, allowing every guest to truly savor the magic of the moment.",
    heroImage: "/images/editorial/garden_wedding.png",
    gallery: placeholderGallery,
    decorHighlights: "Rich burgundy and burnt orange floral arrangements perfectly complemented the palatial architecture. Fairy lights strung around the courtyard created a magical, starry-night ambiance.",
    ceremonyHighlights: "A traditional pheras ceremony under a floral canopy overlooking the lake.",
    receptionHighlights: "A spectacular fireworks display reflecting off the water.",
    bridalOutfitDetails: "Emma chose a heavily embroidered crimson lehenga featuring delicate botanical appliqués, paired with traditional Kundan jewelry.",
    groomOutfitDetails: "Liam wore a tailored ivory sherwani in a soft textured fabric, accented by a deep red safa.",
    vendors: {
      venue: "Taj Lake Palace",
      photographer: "Wanderlust Imagery",
      decorator: "Rajasthan Design Co.",
      makeupArtist: "Radiance Artistry",
      catering: "Taj Events",
      planner: "Regal Weddings",
    },
  },
  "sun-kissed-goa-wedding": {
    slug: "sun-kissed-goa-wedding",
    title: "Sun-Kissed Beachfront Vows",
    coupleNames: "Aisha & Rohan",
    city: "Goa",
    state: "Goa",
    venue: "Taj Exotica",
    date: "November 5, 2025",
    theme: "Beach",
    photographer: "Coastal Clicks",
    planner: "Goa Beach Weddings",
    budget: "₹20–40L",
    guestCount: "200",
    shortDescription: "A vibrant and breezy seaside celebration with pastel themes and endless ocean views.",
    story: "Aisha and Rohan always knew they wanted a wedding by the sea. Their three-day celebration in South Goa was filled with vibrant colors, infectious energy, and the soothing sound of crashing waves. From a colorful mehendi by the pool to a sunset pheras ceremony on the pristine white sands, every moment was designed to be relaxed yet breathtakingly beautiful.",
    heroImage: "/images/editorial/venue_1.png",
    gallery: placeholderGallery,
    decorHighlights: "Soft pastel drapes dancing in the ocean breeze, accented with tropical flowers and warm fairy lights.",
    ceremonyHighlights: "A breathtaking sunset ceremony with the ocean as the ultimate backdrop.",
    receptionHighlights: "A barefoot beach party with fire dancers and an open-air dance floor.",
    bridalOutfitDetails: "A lightweight pastel pink lehenga perfect for the beach, paired with floral jewelry.",
    groomOutfitDetails: "A crisp linen suit in powder blue, keeping it stylish yet comfortable.",
    vendors: {
      venue: "Taj Exotica",
      photographer: "Coastal Clicks",
      decorator: "Tropical Blooms",
      makeupArtist: "Sea Breeze Salon",
      catering: "Goa Catering Co.",
      planner: "Goa Beach Weddings",
    },
  },
  "royal-jaipur-extravaganza": {
    slug: "royal-jaipur-extravaganza",
    title: "A Grand Royal Extravaganza",
    coupleNames: "Meera & Siddharth",
    city: "Jaipur",
    state: "Rajasthan",
    venue: "Rambagh Palace",
    date: "December 12, 2025",
    theme: "Palace",
    photographer: "Royal Lens",
    planner: "The Wedding Design Company",
    budget: "₹40L+",
    guestCount: "600",
    shortDescription: "An opulent palace wedding reflecting the rich heritage and grandeur of Rajasthan.",
    story: "Meera and Siddharth's wedding was nothing short of a modern-day fairytale. Hosted at the magnificent Rambagh Palace, the celebration spanned four days of unadulterated luxury. The events were a beautiful homage to Rajputana heritage, featuring folk performances, elephant processions, and a dining experience fit for royalty. The sheer scale and attention to detail left their guests mesmerized.",
    heroImage: "/images/editorial/royal_wedding.png",
    gallery: placeholderGallery,
    decorHighlights: "Grand floral elephants, thousands of diyas, and deep velvet drapes transformed the palace grounds into a regal paradise.",
    ceremonyHighlights: "A grand baraat featuring vintage cars and traditional Rajasthani drummers.",
    receptionHighlights: "A sit-down royal dinner in the palace gardens with a live Sufi music performance.",
    bridalOutfitDetails: "A custom-designed velvet lehenga with intricate zardozi embroidery, weighing 15kg.",
    groomOutfitDetails: "A royal bandhgala with an antique sword and a polki studded turban.",
    vendors: {
      venue: "Rambagh Palace",
      photographer: "Royal Lens",
      decorator: "Palace Decorators",
      makeupArtist: "Elite Artistry",
      catering: "Rambagh Culinary",
      planner: "The Wedding Design Company",
    },
  },
  "minimalist-kerala-backwaters": {
    slug: "minimalist-kerala-backwaters",
    title: "Serenity in the Backwaters",
    coupleNames: "Anjali & Karthik",
    city: "Kumarakom",
    state: "Kerala",
    venue: "Kumarakom Lake Resort",
    date: "January 20, 2026",
    theme: "Minimal",
    photographer: "Monsoon Studios",
    planner: "Kerala Wedding Planners",
    budget: "₹10–20L",
    guestCount: "150",
    shortDescription: "An intimate, eco-friendly celebration surrounded by the tranquil backwaters of Kerala.",
    story: "Seeking an escape from the city hustle, Anjali and Karthik chose the serene backwaters of Kerala for their intimate wedding. Embracing a minimalist philosophy, they focused on sustainable choices, local traditions, and the natural beauty of their surroundings. The peaceful setting provided the perfect environment for their families to bond and celebrate love in its purest form.",
    heroImage: "/images/editorial/venue_2.png",
    gallery: placeholderGallery,
    decorHighlights: "Lush green banana leaves, simple jasmine strings, and traditional brass lamps created an elegant, earthy vibe.",
    ceremonyHighlights: "A quiet morning Muhurtham ceremony accompanied by traditional Nadaswaram music.",
    receptionHighlights: "A traditional Sadhya feast served on banana leaves, followed by a sunset boat ride.",
    bridalOutfitDetails: "A classic Kerala Kasavu saree with elegant temple jewelry.",
    groomOutfitDetails: "A traditional white mundu and a crisp silk shirt.",
    vendors: {
      venue: "Kumarakom Lake Resort",
      photographer: "Monsoon Studios",
      decorator: "Green Earth Decor",
      makeupArtist: "Natural Beauty",
      catering: "Resort Kitchen",
      planner: "Kerala Wedding Planners",
    },
  },
  "heritage-hyderabad-nikah": {
    slug: "heritage-hyderabad-nikah",
    title: "A Nizami Heritage Nikah",
    coupleNames: "Zara & Kabir",
    city: "Hyderabad",
    state: "Telangana",
    venue: "Taj Falaknuma Palace",
    date: "February 14, 2026",
    theme: "Traditional",
    photographer: "Heritage Captures",
    planner: "Nizami Events",
    budget: "₹40L+",
    guestCount: "350",
    shortDescription: "A breathtaking celebration of love and culture at the iconic Falaknuma Palace.",
    story: "Zara and Kabir celebrated their union with a royal Nikah ceremony at the stunning Taj Falaknuma Palace. The event was steeped in the rich Nizami culture of Hyderabad, from the exquisite culinary spread to the soulful Qawwali performances. The couple's vision was to transport their guests to an era of royal elegance, and the palace's historic charm provided the perfect canvas for their timeless love story.",
    heroImage: "/images/editorial/venue_3.png",
    gallery: placeholderGallery,
    decorHighlights: "Antique chandeliers, fragrant roses, and rich emerald green and gold accents.",
    ceremonyHighlights: "The emotional Nikah ceremony held in the palace's stunning Durbar Hall.",
    receptionHighlights: "A royal feast featuring authentic Hyderabadi biryani and live Qawwali music.",
    bridalOutfitDetails: "A heavy khada dupatta outfit in emerald green, paired with authentic Nizami pearls.",
    groomOutfitDetails: "A golden sherwani with intricate threadwork and a traditional royal turban.",
    vendors: {
      venue: "Taj Falaknuma Palace",
      photographer: "Heritage Captures",
      decorator: "Royal Touch Designs",
      makeupArtist: "Falaknuma Spa & Salon",
      catering: "Taj Kitchens",
      planner: "Nizami Events",
    },
  },
  "garden-glamour-bangalore": {
    slug: "garden-glamour-bangalore",
    title: "Botanical Garden Glamour",
    coupleNames: "Priya & Rahul",
    city: "Bangalore",
    state: "Karnataka",
    venue: "The Tamarind Tree",
    date: "March 10, 2026",
    theme: "Garden",
    photographer: "Lush Lenses",
    planner: "Garden City Weddings",
    budget: "₹10–20L",
    guestCount: "250",
    shortDescription: "A whimsical outdoor wedding surrounded by ancient trees and blooming flora.",
    story: "Priya and Rahul transformed The Tamarind Tree into an enchanted botanical wonderland. Their love for nature dictated every choice, from the eco-friendly invitations to the open-air seating. The pleasant Bangalore weather was the cherry on top, allowing their guests to mingle freely under the canopy of ancient trees and starry skies.",
    heroImage: "/images/editorial/venue_4.png",
    gallery: placeholderGallery,
    decorHighlights: "Suspended floral installations, wooden rustic seating, and endless fairy lights intertwined with the trees.",
    ceremonyHighlights: "An afternoon pheras ceremony under a magnificent banyan tree.",
    receptionHighlights: "An outdoor cocktail party with a live acoustic band.",
    bridalOutfitDetails: "A floral embroidered lehenga in pastel hues, paired with a messy braided hairstyle.",
    groomOutfitDetails: "A tailored beige linen suit with a floral pocket square.",
    vendors: {
      venue: "The Tamarind Tree",
      photographer: "Lush Lenses",
      decorator: "Botanical Decor Co.",
      makeupArtist: "Fresh Face Artistry",
      catering: "Tamarind Kitchen",
      planner: "Garden City Weddings",
    },
  },
  "chennai-temple-wedding": {
    slug: "chennai-temple-wedding",
    title: "A Sacred Temple Union",
    coupleNames: "Sneha & Arjun",
    city: "Chennai",
    state: "Tamil Nadu",
    venue: "Iskcon Temple ECR",
    date: "April 22, 2026",
    theme: "Temple",
    photographer: "Divine Clicks",
    planner: "Chennai Celebrations",
    budget: "Under ₹10L",
    guestCount: "400",
    shortDescription: "A deeply spiritual and traditional South Indian wedding ceremony.",
    story: "Embracing their roots, Sneha and Arjun opted for a highly traditional morning wedding at the picturesque Iskcon Temple on the ECR. The air was filled with the chanting of mantras and the fragrance of jasmine. The ceremony was a beautiful testament to their family's heritage, followed by a simple yet delicious traditional vegetarian feast served on banana leaves.",
    heroImage: "/images/editorial/mandap_design.png",
    gallery: placeholderGallery,
    decorHighlights: "Intricate kolam designs, vibrant marigold strings, and traditional brass lamps.",
    ceremonyHighlights: "The tying of the mangalsutra amidst a shower of yellow rice and flowers.",
    receptionHighlights: "A classical Carnatic music concert post-lunch.",
    bridalOutfitDetails: "A stunning Kanjeevaram silk saree in deep maroon and gold.",
    groomOutfitDetails: "A traditional silk dhoti and angavastram.",
    vendors: {
      venue: "Iskcon Temple ECR",
      photographer: "Divine Clicks",
      decorator: "Traditional Blooms",
      makeupArtist: "Chennai Bridal",
      catering: "Temple Kitchen",
      planner: "Chennai Celebrations",
    },
  },
  "mumbai-sunset-soiree": {
    slug: "mumbai-sunset-soiree",
    title: "A Glamorous Sunset Soirée",
    coupleNames: "Neha & Vikram",
    city: "Mumbai",
    state: "Maharashtra",
    venue: "Taj Lands End",
    date: "May 15, 2026",
    theme: "Luxury",
    photographer: "The Wedding Story",
    planner: "DreamzKraft",
    budget: "₹40L+",
    guestCount: "500",
    shortDescription: "A spectacular high-energy celebration overlooking the Arabian Sea.",
    story: "Neha and Vikram's wedding was the epitome of Mumbai glamour. Hosted at Taj Lands End, the three-day affair featured a star-studded guest list, jaw-dropping decor, and high-energy performances. The highlight was their sunset ceremony overlooking the Bandra-Worli Sea Link, creating a cinematic backdrop for their vows. The celebrations continued into the early hours with a massive after-party.",
    heroImage: "/images/editorial/minimal_wedding.png",
    gallery: placeholderGallery,
    decorHighlights: "Crystal chandeliers, exotic orchids, and mirrored dance floors.",
    ceremonyHighlights: "A sunset exchange of vows on the seaside lawns.",
    receptionHighlights: "A high-octane Bollywood sangeet with celebrity performances.",
    bridalOutfitDetails: "A custom Manish Malhotra lehenga dripping in sequins.",
    groomOutfitDetails: "A sharp black tuxedo by Sabyasachi.",
    vendors: {
      venue: "Taj Lands End",
      photographer: "The Wedding Story",
      decorator: "DreamzKraft Decor",
      makeupArtist: "Namrata Soni",
      catering: "Taj Catering",
      planner: "DreamzKraft",
    },
  },
  "goa-boho-chic": {
    slug: "goa-boho-chic",
    title: "Boho Chic Coastal Vows",
    coupleNames: "Tara & Dev",
    city: "Goa",
    state: "Goa",
    venue: "W Goa",
    date: "October 18, 2026",
    theme: "Destination",
    photographer: "Boho Captures",
    planner: "The Wedding Bartenders",
    budget: "₹20–40L",
    guestCount: "150",
    shortDescription: "A relaxed, bohemian-style wedding set on the vibrant cliffs of Vagator.",
    story: "Tara and Dev wanted a wedding that felt like a weekend getaway with their favorite people. The W Goa provided the perfect vibrant, energetic backdrop for their boho-chic celebration. With pampas grass decor, barefoot dancing, and a mixology bar, the event perfectly captured their laid-back personalities and love for tropical aesthetics.",
    heroImage: "/images/editorial/vendor_photo.png",
    gallery: placeholderGallery,
    decorHighlights: "Macrame backdrops, pampas grass, rattan furniture, and neon signs.",
    ceremonyHighlights: "A cliffside ceremony overlooking the Arabian sea at sunset.",
    receptionHighlights: "An all-night techno and house music beach party.",
    bridalOutfitDetails: "A flowy, backless lace gown perfect for dancing.",
    groomOutfitDetails: "A relaxed floral shirt paired with linen trousers.",
    vendors: {
      venue: "W Goa",
      photographer: "Boho Captures",
      decorator: "Goa Decor Co.",
      makeupArtist: "Boho Glam",
      catering: "W Kitchens",
      planner: "The Wedding Bartenders",
    },
  },
  "udaipur-royal-affair": {
    slug: "udaipur-royal-affair",
    title: "A Regal Udaipur Affair",
    coupleNames: "Ananya & Rohan",
    city: "Udaipur",
    state: "Rajasthan",
    venue: "The Oberoi Udaivilas",
    date: "November 22, 2026",
    theme: "Palace",
    photographer: "Stories by Joseph Radhik",
    planner: "Shaadi Squad",
    budget: "₹40L+",
    guestCount: "400",
    shortDescription: "An incredibly lavish wedding experience at one of the world's most luxurious hotels.",
    story: "Ananya and Rohan's wedding at The Oberoi Udaivilas was a masterclass in luxury. The sprawling palace property was entirely bought out for their guests, who were treated to unparalleled hospitality. The couple exchanged vows on a floating mandap on Lake Pichola, surrounded by a breathtaking floral installation. The entire experience was curated to perfection, offering a truly majestic experience.",
    heroImage: "/images/editorial/hero_venue.png",
    gallery: placeholderGallery,
    decorHighlights: "Floating lotus installations, heavy gold accents, and a literal sea of red roses.",
    ceremonyHighlights: "A dramatic bridal entry on a beautifully adorned boat.",
    receptionHighlights: "A black-tie gala dinner with a Michelin-star curated menu.",
    bridalOutfitDetails: "A regal Sabyasachi red lehenga with heavy heritage jewelry.",
    groomOutfitDetails: "An intricately embroidered ivory sherwani with an emerald necklace.",
    vendors: {
      venue: "The Oberoi Udaivilas",
      photographer: "Stories by Joseph Radhik",
      decorator: "Devika Narain",
      makeupArtist: "Puneet B Saini",
      catering: "Oberoi Culinary",
      planner: "Shaadi Squad",
    },
  },
  "hyderabad-intimate-garden": {
    slug: "hyderabad-intimate-garden",
    title: "An Intimate Garden Soirée",
    coupleNames: "Kavya & Arun",
    city: "Hyderabad",
    state: "Telangana",
    venue: "ITC Kohenur",
    date: "December 5, 2026",
    theme: "Garden",
    photographer: "Candid Tales",
    planner: "Hyderabad Events",
    budget: "₹10–20L",
    guestCount: "200",
    shortDescription: "A beautiful, close-knit gathering featuring sustainable decor and lush greenery.",
    story: "Kavya and Arun envisioned a wedding that was elegant, intimate, and eco-conscious. The outdoor gardens at ITC Kohenur provided a beautiful canvas for their vision. They utilized locally sourced flowers, upcycled decor elements, and digital invitations to minimize their carbon footprint. The result was a warm, joyful celebration that proved luxury and sustainability can go hand in hand.",
    heroImage: "/images/editorial/garden_wedding.png",
    gallery: placeholderGallery,
    decorHighlights: "Locally sourced marigolds, reusable wooden structures, and potted plants as centerpieces.",
    ceremonyHighlights: "A morning ceremony accompanied by a live classical flute performance.",
    receptionHighlights: "A relaxed evening with heartfelt speeches and a farm-to-table dining experience.",
    bridalOutfitDetails: "An elegant handloom silk saree supporting local weavers.",
    groomOutfitDetails: "A simple, tailored raw silk kurta set.",
    vendors: {
      venue: "ITC Kohenur",
      photographer: "Candid Tales",
      decorator: "Eco Decor Hub",
      makeupArtist: "Flawless Looks",
      catering: "ITC Culinary",
      planner: "Hyderabad Events",
    },
  },
  "jaipur-pink-city-romance": {
    slug: "jaipur-pink-city-romance",
    title: "Romance in the Pink City",
    coupleNames: "Ishita & Varun",
    city: "Jaipur",
    state: "Rajasthan",
    venue: "Fairmont Jaipur",
    date: "January 14, 2027",
    theme: "Traditional",
    photographer: "WeddingNama",
    planner: "FNP Weddings",
    budget: "₹20–40L",
    guestCount: "350",
    shortDescription: "A vibrant and joyous celebration of love, culture, and traditional Rajasthani flair.",
    story: "The Fairmont Jaipur set the stage for Ishita and Varun's big fat Indian wedding. The festivities were a riot of colors, featuring everything from a vibrant carnival-themed mehendi to an incredibly energetic sangeet night. The couple's infectious energy spread to every guest, resulting in a celebration that was non-stop fun, laughter, and dancing from start to finish.",
    heroImage: "/images/editorial/vendor_catering.png",
    gallery: placeholderGallery,
    decorHighlights: "Bright pink and orange drapes, mirror work props, and vibrant marigold installations.",
    ceremonyHighlights: "An energetic baraat that lasted over three hours.",
    receptionHighlights: "A massive sangeet with choreographed family performances.",
    bridalOutfitDetails: "A vibrant, multicolored lehenga for the mehendi, and a classic red for the wedding.",
    groomOutfitDetails: "A heavily embroidered sherwani with a matching vibrant safa.",
    vendors: {
      venue: "Fairmont Jaipur",
      photographer: "WeddingNama",
      decorator: "FNP Floral",
      makeupArtist: "Amrit Kaur Artistry",
      catering: "Fairmont Kitchens",
      planner: "FNP Weddings",
    },
  },
  "bangalore-modern-minimalism": {
    slug: "bangalore-modern-minimalism",
    title: "Modern Minimalism Elegance",
    coupleNames: "Riya & Sameer",
    city: "Bangalore",
    state: "Karnataka",
    venue: "The Leela Palace",
    date: "February 28, 2027",
    theme: "Minimal",
    photographer: "Epic Stories",
    planner: "Rings & Roses",
    budget: "₹20–40L",
    guestCount: "250",
    shortDescription: "A sleek, contemporary wedding focusing on clean lines and sophisticated simplicity.",
    story: "Riya and Sameer, both architects, wanted their wedding to reflect their design philosophy: less is more. The Leela Palace offered a grand setting, which they juxtaposed with ultra-minimalist, contemporary decor. The celebration was incredibly chic, featuring monochromatic color palettes, geometric structures, and an emphasis on culinary excellence over visual excess.",
    heroImage: "/images/editorial/vendor_makeup.png",
    gallery: placeholderGallery,
    decorHighlights: "All-white florals, acrylic seating, geometric metal structures, and subtle candlelight.",
    ceremonyHighlights: "A serene, quiet ceremony with an instrumental string quartet.",
    receptionHighlights: "A sophisticated cocktail evening with a bespoke gin bar.",
    bridalOutfitDetails: "A sleek, unembellished white bridal gown with architectural draping.",
    groomOutfitDetails: "A sharp, tailored black suit with a skinny tie.",
    vendors: {
      venue: "The Leela Palace",
      photographer: "Epic Stories",
      decorator: "Modern Edge Decor",
      makeupArtist: "Gloss & Glam",
      catering: "Leela Culinary",
      planner: "Rings & Roses",
    },
  },
  "kerala-beachfront-bliss": {
    slug: "kerala-beachfront-bliss",
    title: "Beachfront Bliss in Kovalam",
    coupleNames: "Shruti & Aditya",
    city: "Kovalam",
    state: "Kerala",
    venue: "The Leela Kovalam",
    date: "March 20, 2027",
    theme: "Beach",
    photographer: "Magic Motion Media",
    planner: "Watermark Event Solutions",
    budget: "₹20–40L",
    guestCount: "300",
    shortDescription: "A spectacular cliffside beach wedding with panoramic views of the Arabian Sea.",
    story: "Perched on a cliff overlooking the Kovalam coastline, Shruti and Aditya's wedding was a mesmerizing blend of luxury and nature. The festivities kicked off with a vibrant Haldi ceremony by the beach and culminated in a grand sunset wedding. The gentle sea breeze and the stunning coastal sunset provided a magical atmosphere that left everyone spellbound.",
    heroImage: "/images/editorial/venue_1.png",
    gallery: placeholderGallery,
    decorHighlights: "Driftwood accents, tropical palms, and soft pastel floral arrangements.",
    ceremonyHighlights: "Exchanging garlands as the sun dipped below the horizon.",
    receptionHighlights: "A lavish seafood buffet featuring the fresh catch of the day.",
    bridalOutfitDetails: "A pastel blue lehenga that perfectly complemented the oceanic backdrop.",
    groomOutfitDetails: "A light grey suit with a relaxed, open-collar shirt.",
    vendors: {
      venue: "The Leela Kovalam",
      photographer: "Magic Motion Media",
      decorator: "Coastal Designs",
      makeupArtist: "Kerala Glamour",
      catering: "The Leela Culinary",
      planner: "Watermark Event Solutions",
    },
  },
  "chennai-heritage-luxury": {
    slug: "chennai-heritage-luxury",
    title: "Heritage Luxury Celebration",
    coupleNames: "Divya & Ashwin",
    city: "Chennai",
    state: "Tamil Nadu",
    venue: "ITC Grand Chola",
    date: "May 10, 2027",
    theme: "Luxury",
    photographer: "Lightsmiths",
    planner: "Marriage Colours",
    budget: "₹40L+",
    guestCount: "800",
    shortDescription: "A massive, ultra-luxurious celebration reflecting the grandeur of the Chola dynasty.",
    story: "Divya and Ashwin's wedding at the ITC Grand Chola was a masterclass in scale and splendor. Welcoming over 800 guests, the wedding was a grand affair featuring towering floral installations, celebrity performances, and an unparalleled culinary spread. Despite the massive scale, the couple ensured every guest felt personally welcomed and attended to, making it a truly memorable luxury experience.",
    heroImage: "/images/editorial/royal_wedding.png",
    gallery: placeholderGallery,
    decorHighlights: "Towering floral columns, intricate gold detailing, and a stage that resembled a palace courtyard.",
    ceremonyHighlights: "A grand entrance by the bride accompanied by classical dancers.",
    receptionHighlights: "A massive gala night featuring a multi-cuisine spread from around the world.",
    bridalOutfitDetails: "A heavy, bespoke Kanjeevaram silk saree woven with real gold threads.",
    groomOutfitDetails: "A majestic silk sherwani with an ornate, jeweled belt.",
    vendors: {
      venue: "ITC Grand Chola",
      photographer: "Lightsmiths",
      decorator: "Grandeur Events",
      makeupArtist: "Bridal Studio",
      catering: "ITC Grand Chola Catering",
      planner: "Marriage Colours",
    },
  }
};
